# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: mvn package

      - name: tomcat deploy
        run: curl -v -u ${{secret.TOM_USER_NAME }}:${{  secret.TOM_PASSWORD  }} -T /home/runner/work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.2.war 'http://ec2-13-234-48-25.ap-south-1.compute.amazonaws.com:8081/manager/text/deploy?path=/github_action_spring/&update=true'
